"""Add email_verified flags

Revision ID: 05db5c7286ea
Revises: 9ee1bf69d1d3
Create Date: 2025-09-19 23:12:29.228486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05db5c7286ea'
down_revision = '9ee1bf69d1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
