"""Add CASCADE to payment foreign keys

Revision ID: 13736f10809b
Revises: 432019e569e4
Create Date: 2025-09-21 11:46:58.419225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13736f10809b'
down_revision = '432019e569e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_transactions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_transactions_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
