"""Add ReviewLog table for review audit trail

Revision ID: 19032a4e55cc
Revises: 4be6f35c9457
Create Date: 2025-10-13 22:54:21.461742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19032a4e55cc'
down_revision = '4be6f35c9457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_created_at'), 'review_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_logs_deck_id'), 'review_logs', ['deck_id'], unique=False)
    op.create_index('ix_review_logs_deck_user_date', 'review_logs', ['deck_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_logs_flashcard_id'), 'review_logs', ['flashcard_id'], unique=False)
    op.create_index('ix_review_logs_user_date', 'review_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index('ix_review_logs_user_date', table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_flashcard_id'), table_name='review_logs')
    op.drop_index('ix_review_logs_deck_user_date', table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_deck_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_created_at'), table_name='review_logs')
    op.drop_table('review_logs')
    # ### end Alembic commands ###
