"""cascade ai_generations FKs

Revision ID: 432019e569e4
Revises: 0c678a3711f2
Create Date: 2025-09-20 02:53:32.358829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432019e569e4'
down_revision = '0c678a3711f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_generations_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ai_generations_deck_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'decks', ['deck_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_generations_deck_id_fkey'), 'decks', ['deck_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ai_generations_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
