"""create teacher_invites table (autogen)

Revision ID: 4be6f35c9457
Revises: 40f74029473b
Create Date: 2025-10-07 15:03:56.757758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4be6f35c9457'
down_revision = '40f74029473b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_invites_code'), 'teacher_invites', ['code'], unique=True)
    op.alter_column('reviews', 'ease',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reviews', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reviews', 'due_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_reviews_card_id'), 'reviews', ['card_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.drop_index(op.f('ix_student_decks_deck'), table_name='student_decks')
    op.drop_index(op.f('ix_student_decks_student'), table_name='student_decks')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_users_teacher_demo'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_teacher_demo'), 'users', ['teacher_id', 'is_demo'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_student_decks_student'), 'student_decks', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_decks_deck'), 'student_decks', ['deck_id'], unique=False)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_card_id'), table_name='reviews')
    op.alter_column('reviews', 'due_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('reviews', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('reviews', 'ease',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('2.5'),
               existing_nullable=False)
    op.drop_index(op.f('ix_teacher_invites_code'), table_name='teacher_invites')
    op.drop_table('teacher_invites')
    # ### end Alembic commands ###
