"""Add quiz tables

Revision ID: 83c858c3c113
Revises: 894854edcd68
Create Date: 2025-10-18 19:04:48.539642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83c858c3c113'
down_revision = '894854edcd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_type', sa.String(length=32), nullable=False),
    sa.Column('deck_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_created', 'quizzes', ['started_at'], unique=False)
    op.create_index('idx_quiz_user_status', 'quizzes', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_deck_id'), 'quiz_answers', ['deck_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_flashcard_id'), 'quiz_answers', ['flashcard_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_quiz_id'), 'quiz_answers', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_quiz_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_flashcard_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_deck_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index('idx_quiz_user_status', table_name='quizzes')
    op.drop_index('idx_quiz_created', table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
