"""Add quiz tracking to UsageLimits

Revision ID: 894854edcd68
Revises: 19032a4e55cc
Create Date: 2025-10-18 17:24:28.398466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894854edcd68'
down_revision = '19032a4e55cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_limits', sa.Column('week_key', sa.String(length=10), nullable=True))
    op.add_column('usage_limits', sa.Column('quiz_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('idx_usage_user_week', 'usage_limits', ['user_id', 'week_key'], unique=False)
    op.create_index(op.f('ix_usage_limits_week_key'), 'usage_limits', ['week_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_limits_week_key'), table_name='usage_limits')
    op.drop_index('idx_usage_user_week', table_name='usage_limits')
    op.drop_column('usage_limits', 'quiz_count')
    op.drop_column('usage_limits', 'week_key')
    # ### end Alembic commands ###
