"""Add ON DELETE CASCADE to user child FKs

Revision ID: 9ee1bf69d1d3
Revises: b9881025f250
Create Date: 2025-09-19 22:40:11.507658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee1bf69d1d3'
down_revision = 'b9881025f250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('otp_codes_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('trusted_devices_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trusted_devices_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('otp_codes_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
