"""billing: add subscriptions, payment_transactions, usage_limits

Revision ID: a10064441ca3
Revises: f81e952dbae9
Create Date: 2025-09-06 16:14:32.257132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10064441ca3'
down_revision = 'f81e952dbae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'card', 'bank', name='payment_methods_v1'), server_default='mpesa', nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='intasend', nullable=False),
    sa.Column('api_ref', sa.String(length=120), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'pending', 'succeeded', 'failed', 'refunded', name='transaction_status_v1'), server_default='initiated', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_api_ref'), ['api_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_ref'), ['provider_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('monthly', name='plan_types_v1'), server_default='monthly', nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', 'pending', name='subscription_status_v1'), server_default='pending', nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), server_default='100', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=True)

    op.create_table('usage_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('ai_prompt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_quota', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month_key', name='uq_usage_user_month')
    )
    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_limits_month_key'), ['month_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_limits_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_limits_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_limits_month_key'))

    op.drop_table('usage_limits')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_ref'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_api_ref'))

    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
