"""Add ON DELETE CASCADE to all user foreign keys

Revision ID: c6e5600afabc
Revises: 312c65738a5d
Create Date: 2025-09-22 20:53:04.653681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e5600afabc'
down_revision = '312c65738a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_decks_user_id'))
        batch_op.drop_constraint(batch_op.f('decks_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_flashcards_deck_id'))
        batch_op.drop_constraint(batch_op.f('flashcards_deck_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'decks', ['deck_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_otp_codes_created_at'))
        batch_op.drop_index(batch_op.f('idx_otp_codes_expires_at'))
        batch_op.drop_index(batch_op.f('idx_otp_codes_user_id'))

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_transactions_created_at'))
        batch_op.drop_index(batch_op.f('idx_payment_transactions_user_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_progress_deck_id'))
        batch_op.drop_index(batch_op.f('idx_progress_flashcard_id'))
        batch_op.drop_index(batch_op.f('idx_progress_user_deck'))
        batch_op.drop_index(batch_op.f('idx_progress_user_flashcard'))
        batch_op.drop_index(batch_op.f('idx_progress_user_id'))
        batch_op.drop_constraint(batch_op.f('progress_deck_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('progress_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'decks', ['deck_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subscriptions_end_date'))
        batch_op.drop_index(batch_op.f('idx_subscriptions_status'))
        batch_op.drop_index(batch_op.f('idx_subscriptions_user_id'))

    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trusted_devices_user_id'))

    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usage_limits_user_id'))

    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_credits_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_stats_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_stats_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_credits_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usage_limits_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_trusted_devices_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_subscriptions_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('progress_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('progress_deck_id_fkey'), 'decks', ['deck_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_progress_user_flashcard'), ['user_id', 'flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_progress_user_deck'), ['user_id', 'deck_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_progress_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_progress_deck_id'), ['deck_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payment_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_transactions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_otp_codes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_codes_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('flashcards_deck_id_fkey'), 'decks', ['deck_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_flashcards_deck_id'), ['deck_id'], unique=False)

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('decks_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_decks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
