"""baseline from current models

Revision ID: ddb94cd5188f
Revises: 
Create Date: 2025-08-31 23:05:47.442153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb94cd5188f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress', 'interval',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.drop_column('progress', 'ease_factor')
    op.drop_column('progress', 'repetitions')
    op.drop_column('progress', 'inerval')
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.add_column('progress', sa.Column('inerval', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('progress', sa.Column('repetitions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('progress', sa.Column('ease_factor', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'2.5'::double precision"), autoincrement=False, nullable=False))
    op.alter_column('progress', 'interval',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
